[package]
name = "tiny-compiler-rust"
version = "0.1.0"
authors = ["Alvaro Tinoco <alv_tinoco_97@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "0.7.2"
